CUSTOM Windows API: D:/MyProject/VC++ ver 15.00/CuCustomWndAPI/include/ccw_Error.h File Reference
ccw_Error.h File Reference
Error list and description.
Enumerations
enum CcwResult : DWORD {
CcwResult_OK = 0 ,
CcwResult_OpenDeviceError = 1 ,
CcwResult_UnsupportedFunction = 2 ,
CcwResult_InvalidParameter = 3 ,
CcwResult_SmallBuffer = 4 ,
CcwResult_NullPointer = 5 ,
CcwResult_NotInitialized = 6 ,
CcwResult_InvalidDeviceID = 7 ,
CcwResult_ReadError = 8 ,
CcwResult_WriteError = 9 ,
CcwResult_UnsupportedDevice = 10 ,
CcwResult_CommunicationError = 11 ,
CcwResult_BarcodeUnsupportedError = 12 ,
CcwResult_BarcodeWidthError = 13 ,
CcwResult_DeviceAlreadyOpenError = 14 ,
CcwResult_PrinterNotExistError = 15 ,
CcwResult_UnknowPrinterError = 16 ,
CcwResult_OpenFileError = 17 ,
CcwResult_CommunicationBusy = 18 ,
CcwResult_CodePageUnsupported = 19 ,
CcwResult_UnknowError = 0xFFFFFFFF
}
Functions
static const wchar_t * CcwResultToText (CcwResult result)
Detailed Description
Error list and description.
Enumeration Type Documentation
CcwResult
enum CcwResult : DWORD
Error list
Enumerator
CcwResult_OK
All OK.
CcwResult_OpenDeviceError
Open Port/Device Error.
CcwResult_UnsupportedFunction
Unsupported Function.
CcwResult_InvalidParameter
Invalid parameter.
CcwResult_SmallBuffer
Small buffer.
CcwResult_NullPointer
Null or invalid pointer.
CcwResult_NotInitialized
Library not initialized.
CcwResult_InvalidDeviceID
Invalid device ID.
CcwResult_ReadError
The device doesn't answer.
CcwResult_WriteError
Write error.
CcwResult_UnsupportedDevice
Unsupported Device.
CcwResult_CommunicationError
Error communication data.
CcwResult_BarcodeUnsupportedError
Barcode type unsupported.
CcwResult_BarcodeWidthError
Barcode width Error.
CcwResult_DeviceAlreadyOpenError
Open Port/Device Error.
CcwResult_PrinterNotExistError
Printer doesn't exist Error.
CcwResult_UnknowPrinterError
Printer unknow Error.
CcwResult_OpenFileError
File not found or error during the open.
CcwResult_CommunicationBusy
Communication busy.
CcwResult_CodePageUnsupported
Code page unsupported.
CcwResult_UnknowError
Unknow Error.
Function Documentation
CcwResultToText()
static const wchar_t * CcwResultToText (CcwResult result) static
Translates CcwResult to the related text message.
Parameters
result Result value to be translated to text.
Returns
A null-terminated string containing the description.
Referenced by Align(), BinFileToPrintSpooler(), CloseAllDevices(), CloseDevice(), CommClearReadBuffer(), CommClearWriteBuffer(), CommGetReadTimeout(), CommGetWriteTimeout(), CommRead(), CommSetReadTimeout(), CommSetWriteTimeout(), CommWrite(), Cut(), DeInitLibrary(), Eject(), EjectWithTimeout(), EnumCOMPorts(), EnumETHDevices(), EnumInstalledPrinters(), EnumUSBDevices(), Feed(), GetAPIVersion(), GetCapCodepagesList(), GetCapCommPortType(), GetCapPrintAvailable(), GetCapPrinterResolution(), GetCapPrintWidth(), GetGraphicsTopMargin(), GetInfoDeviceModel(), GetInfoFirmwareVersion(), GetInfoPrinterId(), GetPrinterFullStatus(), GetVariable(), InitLibrary(), OpenCashDrawer(), OpenInstalledPrinter(), OpenPrinterCOM(), OpenPrinterCOMEx(), OpenPrinterETH(), OpenPrinterETHEx(), OpenPrinterUSB(), OpenPrinterUSBEx(), Present(), PrintBarcodeBuffer(), PrintBarcodeString(), PrinterIsReady(), PrintImageFromPath(), PrintRawImage(), PrintText(), PrintTextEx(), PrintTextUTF8(), PrintTextUTF8Ex(), RawDataToPrintSpooler(), SetCapPrintWidth(), SetGraphicsTopMargin(), SetGrModeToBlackWhite(), SetIgnoreWhiteImages(), SetPageModeToRoll(), SetVariable(), and TransactionPrint().